mysql:
  host: 127.0.0.1
  port: 3306
  db: blog
  user: root
  password: "123456"
  level: ""
logger:
  level: info
  prefix: '[gvb]'
  direct: ./logs
  showLine: false
  logInConsole: false
system:
  host: 0.0.0.0
  port: 8080
  env: debug # debug release