mysql:
    host: 127.0.0.1
    port: 3306
    db: gvb_blog
    user: root
    password: "123456"
    level: ""
logger:
    level: info
    prefix: '[gvb]'
    direct: ./logs
    showLine: false
    logInConsole: false
system:
    host: 0.0.0.0
    port: 8080
    env: debug
site_info:
    created_at: "2024-04-26"
    bei_an: 京ICP备2021001234号-1
    title: 十一月的情书个人博客
    wechat_qr_image: https://q1.qlogo.cn/g?b=qq&nk=123456&s=640
    qq_qr_image: https://q1.qlogo.cn/g?b=qq&nk=123456&s=640
    qq_number: "2428537532"
    version: 1.0.0
    email: 123456@qq.com
    github: https://github.com/dashboard
    gitee: https://gitee.com/123456
    name: 张柏芝
    job: 程序员
    address: 江苏徐州
    slogan: 人生如逆旅，我亦是行人
    slogan_en: Life is like a journey, I am also a walker
