mysql:
    host: 127.0.0.1
    port: 3306
    db: gvb_blog
    user: root
    password: "123456"
    level: ""
logger:
    level: info
    prefix: '[gvb]'
    direct: ./logs
    showLine: false
    logInConsole: false
system:
    host: 0.0.0.0
    port: 8080
    env: debug
uploads:
    size: 2
    path: uploads/settings_images
site_info:
    created_at: "2024-06-26"
    bei_an: 京ICP备2021001234号-1
    title: 十一月的情书个人博客
    wechat_qr_image: https://q1.qlogo.cn/g?b=qq&nk=123456&s=640
    qq_qr_image: https://q1.qlogo.cn/g?b=qq&nk=123456&s=640
    qq_number: "2428537532"
    version: 2.0.0
    email: 123456@qq.com
    github: https://github.com/dashboard
    gitee: https://gitee.com/123456
    name: 张柏芝
    job: 程序员
    address: 江苏徐州
    slogan: The things we pursue throughout our lives are actually there from the beginning, it's just that we realize it later
    slogan_en: Life is like a journey, I am also a walker
qq:
    app_id: 1103782715_appid
    key: 1103782715_key
    redirect: 跳转路径
email:
    host: smtp.qq.com
    port: 306
    user: 1103782715@qq.com
    password: ahvvuoqmrmiyfjhj
    default_from_email: 默认邮箱
    user_ssl: true
    user_tls: false
    authorization_code: ahvvuoqmrmiyfjhj
jwt:
    expires: 48
    issuer: gin_chat
    jwt_key: asdfghjkl
    grant_scope: chat,read user info
    subject: chat
qi_niu:
    enable: true
    access_key: Z9f1VLVDia5PWNwOihr49l_XBE7YNMmnemskWv1A
    secret_key: ouuJwrcx_aWmjRsMH9jMqz_XjLEphpyGTvQXfBJS
    bucket: shiyiyue
    cdn: ""
    zone: z2
    size: 5
