// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/advert/create": {
            "post": {
                "description": "创建广告",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "广告管理"
                ],
                "summary": "创建广告",
                "parameters": [
                    {
                        "description": "广告的参数",
                        "name": "data",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/service.AdvertResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/advert/delete": {
            "delete": {
                "description": "删除广告",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "广告管理"
                ],
                "summary": "删除广告",
                "parameters": [
                    {
                        "description": "删除广告所需参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/common.RemoveFileList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/advert/show": {
            "get": {
                "description": "获取广告列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "广告管理"
                ],
                "summary": "获取广告列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页",
                        "name": "currentPage",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索参数",
                        "name": "key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "一页显示多少条数据",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "获取广告列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片管理"
                ],
                "summary": "更新图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "更新",
                        "name": "data",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/advert/update/:id": {
            "put": {
                "description": "编辑广告",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "广告管理"
                ],
                "summary": "编辑广告",
                "parameters": [
                    {
                        "description": "编辑广告所需参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.AdvertResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/image": {
            "post": {
                "description": "添加图片",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片管理"
                ],
                "summary": "添加图片",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页",
                        "name": "currentPage",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索参数",
                        "name": "key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "一页显示多少条数据",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/imageList": {
            "get": {
                "description": "获取图片列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片管理"
                ],
                "summary": "获取图片列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页",
                        "name": "currentPage",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索参数",
                        "name": "key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "一页显示多少条数据",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "批量删除",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片管理"
                ],
                "summary": "批量删除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页",
                        "name": "currentPage",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索参数",
                        "name": "key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "一页显示多少条数据",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/menu/create": {
            "post": {
                "description": "创建菜单",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "创建菜单",
                "parameters": [
                    {
                        "description": "菜单的参数",
                        "name": "data",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/service.MenuService"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/menu/delete": {
            "delete": {
                "description": "批量删除菜单",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "批量删除菜单",
                "parameters": [
                    {
                        "description": "删除菜单的参数",
                        "name": "data",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/common.RemoveFileList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/menu/menuInfo": {
            "get": {
                "description": "获取图片的基础信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "获取图片的基础信息id，path，title",
                "parameters": [
                    {
                        "description": "获取图片的基础信息id【不需要参数】",
                        "name": "data",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/menu/show": {
            "get": {
                "description": "获取所有图片",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "获取所有图片",
                "parameters": [
                    {
                        "description": "获取所有图片【不需要参数】",
                        "name": "data",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/menu/update": {
            "put": {
                "description": "编辑菜单",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "编辑菜单",
                "parameters": [
                    {
                        "description": "菜单的参数",
                        "name": "data",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/service.MenuService"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.RemoveFileList": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "service.AdvertResponse": {
            "type": "object",
            "required": [
                "href",
                "images",
                "is_show",
                "title"
            ],
            "properties": {
                "href": {
                    "description": "广告链接",
                    "type": "string"
                },
                "images": {
                    "description": "图片",
                    "type": "string"
                },
                "is_show": {
                    "description": "是否显示",
                    "type": "boolean"
                },
                "title": {
                    "description": "广告标题 唯一",
                    "type": "string"
                }
            }
        },
        "service.ImageSortList": {
            "type": "object",
            "properties": {
                "imageId": {
                    "type": "integer"
                },
                "sort": {
                    "type": "integer"
                }
            }
        },
        "service.MenuService": {
            "type": "object",
            "required": [
                "Path",
                "Title",
                "sort"
            ],
            "properties": {
                "Path": {
                    "description": "英文=\u003e路径显示",
                    "type": "string"
                },
                "Title": {
                    "description": "中文 =\u003e导航条显示",
                    "type": "string"
                },
                "abstract": {
                    "description": "简介",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "abstractTime": {
                    "description": "简介切换时间",
                    "type": "integer"
                },
                "imageSort": {
                    "description": "图片排序顺序",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.ImageSortList"
                    }
                },
                "menuTime": {
                    "description": "切换时间",
                    "type": "integer"
                },
                "slogan": {
                    "type": "string"
                },
                "sort": {
                    "description": "菜单序号",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1：8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "gvb_API",
	Description:      "API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
